# Generated by Django 5.0.4 on 2024-04-08 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_order_onu_alter_order_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha De Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onu',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='router',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha De Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='router',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
    ]
