# Generated by Django 5.0.4 on 2024-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_onu_date_created_onu_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='not_assign',
            field=models.BooleanField(default=False, verbose_name='No asignar'),
        ),
    ]
