# Generated by Django 5.0.4 on 2024-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_order_not_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Catastrado'),
        ),
    ]
