# Generated by Django 5.0.6 on 2024-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_order_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='not_assign_reason',
            field=models.IntegerField(blank=True, choices=[(0, 'Cliente no responde'), (1, 'Cliente no disponible'), (2, 'Cliente retira el servicio'), (3, 'En espera de adecuación'), (4, 'Caja NAP llena'), (5, 'Inspección'), (6, 'Asignación retirada'), (7, 'Otro')], null=True, verbose_name='Motivo de demora'),
        ),
    ]
